services:
  composer:
    image: composer
    volumes:
      - .:/app
    command: composer install
    
  app:
    container_name: app
    build: 
      context: .
    volumes:
      - ./src:/app
      - ./vendor:/app/vendor
    ports:
      - 8080:80
