services:    
  app:
    build: 
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/app
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
    ports:
      - 8080:80
    command: sh -c "composer install && apache2-foreground"
    develop:
      watch:
        - action: restart
          path: .env
